### PR TITLE
Add links to the Go SDK

### PR DESCRIPTION
**Pull request by herohde**

### CODE REVIEW

**Comment by herohde** [comment]
R: @melap

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 361 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/361.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/CouchDB/api/python?tree=jobs%5Bname%2Ccolor%5D.

**Comment by melap** [comment]
@asfgit merge

**Pull request merged**
