### PR TITLE
Regenerate website for new 2.2 javadoc/pydoc

### PR DESCRIPTION
**Pull request by melap**
The new 2.2 javadoc/pydoc didn't get properly regenerated into the content directory so 404ing.

### CODE REVIEW

**Comment by melap** [comment]
R: @reuvenlax @aaltay

**Comment by reuvenlax** [comment]
Lgtm

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
Failure unrelated to the PR, will try again in a bit:
gpg: keyserver timed out

**Comment by melap** [comment]
retest this please

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 358 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/maven-box/job/maven-release/api/python?tree=jobs%5Bname%2Ccolor%5D.. URL: http://mergebot-vm.apache.org/beam-website/358.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/maven-box/job/maven-release/api/python?tree=jobs%5Bname%2Ccolor%5D.

**Comment by melap** [comment]
@asfgit merge

**Comment by aaltay** [comment]
LGTM.

Is there a staged version?

**Comment by asfgit** [comment]
MergeBot: Merge: PR 358 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/96/api/python?depth=1&tree=building.. URL: http://mergebot-vm.apache.org/beam-website/358.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/96/api/python?depth=1&tree=building.

**Comment by melap** [comment]
Yes, it's staged at http://apache-beam-website-pull-requests.storage.googleapis.com/358/index.html
Not sure why the stage job is not commenting the links anymore.

**Comment by melap** [comment]
@asfgit merge

**Pull request merged**
