### PR TITLE
[BEAM-501] New skin proposal

### PR DESCRIPTION
**Pull request by jbonofre**
This a new skin proposal. It's still a work in progress, but it already allows people to take a look, provide feedback, and upgrade.

### CODE REVIEW

**Comment by aljoscha** [comment]
Would it be possible to host a preview somewhere?

**Comment by jbonofre** [comment]
@aljoscha yup, it's already available there: http://maven.nanthrax.net/beam/ (just the homepage)

**Comment by davorbonaci** [comment]
I'm on this! Review & merge coming up shortly!

**Comment by davorbonaci** [comment]
Merged (site not rebuilt).

**Pull request closed without merging**
