### PR TITLE
Update source-repository.md

### PR DESCRIPTION
**Pull request by mattl**
This makes a promised link actually a link.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/683/

Jenkins built the site at commit id 82a5ace4d9caa563c313c22cad4058074eaa23b8 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/317/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by melap** [comment]
@kennknowles for merge

**Comment by kennknowles** [comment]
Incidentally, it seems like this page should mention the fact that we store the write-only source of truth there but do everything via the github mirror.

**Comment by kennknowles** [comment]
@asfgit merge

**Pull request closed without merging**
