### PR TITLE
[BEAM-5603] fix broken 2.6.0 download links

### PR DESCRIPTION
**Pull request by yifanzou**
*Please* add a meaningful description for your change here.

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/PULL_REQUEST_NUMBER/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by yifanzou** [comment]
+R: @melap @chamikaramj

**Comment by melap** [comment]
@asfgit merge

**Comment by yifanzou** [comment]
Thanks.

**Comment by melap** [comment]
@asfgit merge

**Comment by melap** [comment]
Hmm, I think maybe mergebot isn't working, @jasonkuster or @alanmyrvold could you please check and restart mergebot?

**Comment by melap** [comment]
@asfgit merge

**Comment by melap** [comment]
@asfgit merge

**Pull request merged**
