### PR TITLE
change apache kafka docs link

### PR DESCRIPTION
**Pull request by joeyfezster**
change link to kafka docs

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/659/

Jenkins built the site at commit id 46109367598a6b414974c22ad82eb478754bf9db with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/307/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/660/

Jenkins built the site at commit id d7b0380bed2f32505e4af791ec9684847ff3a2b6 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/307/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by aviemzur** [comment]
Hi Joey,

Following the discussion in the dev list. Could be better here to have a README file where the original link leads, instead of changing the link.

This README file can also contain other missing information about using `KafkaIO` such as adding a Maven dependency.

**Comment by joeyfezster** [comment]
maybe it's better to keep the original link, and add a README file at the kafka class level. as pointed out by @aviemzur

**Pull request closed without merging**
