### PR TITLE
[BEAM-2510] Link to SDK pages from the quickstarts

### PR DESCRIPTION
**Pull request by melap**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/686/

Jenkins built the site at commit id 8b94fc124e6c2ba953ea3c7810435e0414b4f517 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/319/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by melap** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/687/

Jenkins built the site at commit id 8b94fc124e6c2ba953ea3c7810435e0414b4f517 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/319/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by tgroh** [comment]
@asfgit merge

**Pull request merged**
