### PR TITLE
Fixed an example of shading the application jar to run it on Spark

### PR DESCRIPTION
**Pull request by aromanenko-dev**

### CODE REVIEW

**Comment by iemejia** [comment]
@asfgit merge

**Comment by iemejia** [comment]
@asfgit merge

**Comment by iemejia** [comment]
@asfgit merge

**Comment by iemejia** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Clone failed. Please try again.

**Comment by asfgit** [comment]
MergeBot: Merge: PR 369 in state error with description Unexpected Error: (sqlite3.OperationalError) database or disk is full [SQL: u'INSERT INTO work_item_status (project_name, item_id, timestamp, status, info) VALUES (?, ?, ?, ?, ?)'] [parameters: ('beam-website', 369, '2018-01-10 21:15:54.484793', 'ERROR', 'Exception: Clone failed. Please try again.')].. URL: http://mergebot-vm.apache.org/beam-website/369.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: (sqlite3.OperationalError) database or disk is full [SQL: u'INSERT INTO work_item_status (project_name, item_id, timestamp, status, info) VALUES (?, ?, ?, ?, ?)'] [parameters: ('beam-website', 369, '2018-01-10 21:15:54.484793', 'ERROR', 'Exception: Clone failed. Please try again.')].

**Comment by iemejia** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 369 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/369.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 369 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/369.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
looks like there are no free machines for the verification job. :disappointed: will try again later.
https://builds.apache.org/label/beam/load-statistics?auto_refresh=false

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
