### PR TITLE
Update Gemfile.lock

### PR DESCRIPTION
**Pull request by kennknowles**
Keeping our deps recent.

### CODE REVIEW

**Comment by kennknowles** [comment]
Curiously enough, the website test is accurate. All the ids for anchors seem to be prefixed with a number, at http://apache-beam-website-pull-requests.storage.googleapis.com/388/documentation/programming-guide/index.html#adding-timestamps-to-a-pcollections-elements etc

**Comment by iemejia** [comment]
Any chance to get jekyll updated too? From a local test it seems to be way faster than version 3.2.

**Comment by kennknowles** [comment]
This was just a `bundle update` but it looks like we pin the Jekyll version in the `Gemfile` so it doesn't get updated. I'm assuming that will cause another round of churn. I think @melap is the best person to know how to schedule it.

**Comment by melap** [comment]
I'm OK if you want to go ahead and update it to give it a try now. I already need to go through everything and update all of the anchor links due to the kramdown upgrade, so now's actually a good time. get all the pain over with at once. :smile: at worst, can just undo the jekyll update and I'll look into an overhaul in a different PR.

**Comment by melap** [comment]
I opened a PR to your branch that should fix all of the anchor issues from the upgrade

**Comment by kennknowles** [comment]
Merged your PR, thanks!

**Comment by melap** [comment]
I'm thinking it actually may be best to merge this now and open a separate PR that updates jekyll.

**Comment by kennknowles** [comment]
LGTM

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Custom preparation command failed. Check logs for more information.

**Comment by kennknowles** [comment]
Looks like the commit made it to the `mergebot` branch but not to `asf-site`.

**Comment by kennknowles** [comment]
I think it is took the bot down? The link for logs is dead.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
These verification job failures are false positives that aren't really problems, will try this again later.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Custom preparation command failed. Check logs for more information.

**Comment by kennknowles** [comment]
@asfgit merge

**Pull request merged**
