### PR TITLE
Publish release 2.1.0

### PR DESCRIPTION
**Pull request by jbonofre**
R: @davorbonaci

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/556/

Jenkins built the site at commit id cb0bcad794800141d07f448f53e3e47603ff1a2b with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/270/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/617/

Jenkins built the site at commit id cb0bcad794800141d07f448f53e3e47603ff1a2b with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/270/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by aaltay** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/642/

Jenkins built the site at commit id cb0bcad794800141d07f448f53e3e47603ff1a2b with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/270/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Pull request closed without merging**
