### PR TITLE
[BEAM-4828] Updated documentation, added SQS BEAM-4828 to In-Progress

### PR DESCRIPTION
**Pull request by lukecwik**
Duplicate https://github.com/apache/beam/pull/5995

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/PULL_REQUEST_NUMBER/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by lukecwik** [comment]
CC: @JohnRudolfLewis

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 501 in state failure with description Final push failed, but verification succeeded. This may have occurred because of a manual merge into the repo. Please check logs and try again.. URL: http://mergebot-vm2.apache.org:8080/beam-website/501.

**Comment by asfgit** [comment]
Error: Final push failed, but verification succeeded. This may have occurred because of a manual merge into the repo. Please check logs and try again.

**Pull request merged**
