### PR TITLE
Fix dead link

### PR DESCRIPTION
**Pull request by melap**
R: @kennknowles  (as you have the context of the move)

### CODE REVIEW

**Comment by melap** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 333 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/Mesos/api/python?tree=jobs%5Bname%2Ccolor%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ec5e87150>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)).. URL: http://mergebot-vm.apache.org/beam-website/333.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/Mesos/api/python?tree=jobs%5Bname%2Ccolor%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f7ec5e87150>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)).

**Comment by lukecwik** [comment]
@asfgit merge

**Pull request merged**
