### PR TITLE
Publish 2.7.0 release

### PR DESCRIPTION
**Pull request by charlesccychen**

### CODE REVIEW

**Comment by charlesccychen** [comment]
retest this please

**Comment by melap** [comment]
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/549/index.html

Quick note on this, when you add the downloads page changes for 2.7.0 to this PR, all 2.6.0 related download links will also need to be updated to point to archive.apache.org links, or they will 404 after 2.7.0 is on dist

**Comment by charlesccychen** [comment]
R: @chamikaramj

**Comment by charlesccychen** [comment]
@asfgit merge

**Comment by charlesccychen** [comment]
@asfgit merge

**Pull request closed without merging**
