### PR TITLE
 [BEAM-4827] Add Nexmark dashboards to nexmark page on the website

### PR DESCRIPTION
**Pull request by echauchot**
I saw while testing that rake failed due to a reference to pom.xml in dataflow in the relaease guide that no longer exist now that we moved to gradle.
I added another commit remove the pom.xml reference

R: @akedin 
R: @melap 

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/500/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by echauchot** [comment]
Beware, these dashboards are writable by anyone, we need before merging to reduce the rights on this dashboards.

**Comment by apilloud** [comment]
LGTM.

**Comment by echauchot** [comment]
retest this please

**Comment by echauchot** [comment]
@melap actually, there is no credentials issues. I tested to modify dashboards with another google account and I can modify SQL, refresh the graph, clic save (with no error message) but when I reopen the dashboard it is not modified. We can merge the PR. There are timeouts issues with keys. Can you check it and merge the PR ? I'm leaving on vacations.

**Comment by echauchot** [comment]
In the staging log it says that it is sucessfull but that there was a timeout in updating the status of the PR in github. So I'm merging the PR

**Comment by echauchot** [comment]
@asfgit merge

**Comment by echauchot** [comment]
retest this please

**Comment by echauchot** [comment]
key server communication failed. Not related to this PR

**Comment by echauchot** [comment]
@asfgit merge

**Comment by echauchot** [comment]
@iemejia can you merge this PR while I'm on holidays, there are still timeouts right now

**Pull request closed without merging**
