### PR TITLE
Add 0.4.0 release

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @davorbonaci 
CC: @dhalperi

**Comment by dhalperi** [comment]
Build failures are somewhat expected -- HTMLProofer is catching a newly-bad link from Python code rename.

**Comment by dhalperi** [comment]
I just merged #116. If you rebase on top of asf-site, should pass.

Thanks, JB!

**Comment by dhalperi** [comment]
I reviewed the PR manually; the files that changed outside of regenerating javadoc appear to be:

```
_config.yml                                        |     2 +-
 src/documentation/sdks/javadoc/current.md          |     2 +-
 src/get-started/downloads.md                       |     5 +
 ```

We should probably put Javadoc in its own commit for future releases so that we can ignore that second commit.

These changes look fine to me. LGTM once released.

**Comment by davorbonaci** [comment]
retest this please

**Comment by davorbonaci** [comment]
LGTM. Ready for merge after the release is pushed to Maven Central.

**Comment by jbonofre** [comment]
Rebased to test travis. I gonna merge when tests are OK.

**Pull request merged**
