### PR TITLE
Manually add missing generated files

### PR DESCRIPTION
**Pull request by melap**
A couple things got missed when merging. issue #321 is filed, but until then, this will fix the 404s.
CC: @jasonkuster

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/717/

Jenkins built the site at commit id c43098e8e0a0d49fe99f70e2ad26ab97210ae28b with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/325/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by melap** [comment]
R: @tgroh or @kennknowles

**Comment by kennknowles** [comment]
My mistake, I had failed to check out the actual `asf-site` branch.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 325 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/55/api/python?depth=1&tree=building.. URL: http://mergebot-vm.apache.org/beam-website/325.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/55/api/python?depth=1&tree=building.

**Comment by melap** [comment]
This might need another kick, it doesn't appear it succeeded.

**Comment by kennknowles** [comment]
@asfgit merge

**Pull request closed without merging**
