### PR TITLE
Fixed Spelling.

### PR DESCRIPTION
**Pull request by jimmycasey**
Hi there, 
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy

*Please* add a meaningful description for your change here.

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/PULL_REQUEST_NUMBER/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by melap** [comment]
The robot might not like the change in the generated context directory version, we shall see!

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by jimmycasey** [comment]
I didn't even know you could do that, cool.

**Comment by melap** [comment]
yeah, it didn't like that. @jimmycasey thanks for your PR, could you please remove the change to content/js/language-switch.js from your PR and I'll attempt another merge? the files in the content directory are auto-generated from src, so the src version is all that needs to be changed. thanks!

**Comment by melap** [comment]
Hi @jimmycasey ,  coming back to this, could you remove that file and I'll get this merged? thanks!

**Comment by swegner** [comment]
Looks like this is fixed in https://github.com/apache/beam/pull/6094. Closing.

**Pull request closed without merging**
