### PR TITLE
Update json version (1.8.3 -> 2.1.0)

### PR DESCRIPTION
**Pull request by ThatRfernand**
1.8.3 is quite outdated and incompatible with Ruby 2.4.0+. Note the README.md says a contributor needs Ruby >= 2.2.0 for this project.

http://apache-beam-website-pull-requests.storage.googleapis.com/513/index.html

### CODE REVIEW

**Comment by ThatRfernand** [comment]
r: @melap 

Tests seem to be failing contacting a key server:

gpgkeys: key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB can't be retrieved

**Comment by ThatRfernand** [comment]
retst this please

**Comment by ThatRfernand** [comment]
retest this please

**Comment by ThatRfernand** [comment]
R: @melap

**Comment by pabloem** [comment]
Hi @ThatRfernand 
It seems that json 1.8.3 was removed as a requirement [a few months back](https://github.com/apache/beam-site/commit/e1fe18be8fa100a49e73e3844db03124f18769fb#diff-e79a60dc6b85309ae70a6ea8261eaf95). Do we still need this?

**Comment by ThatRfernand** [comment]
I think you're right -- the dependencies that need json seem to be pulling the right thing when not specified. Thanks!

**Pull request closed without merging**
