### PR TITLE
[BEAM-1073] Do not use BeautifulSoup prettify, which is known to corrupt HTML

### PR DESCRIPTION
**Pull request by kennknowles**
Opening this to see what happens to the staged HTML when we don't prettify.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
LGTM, nice.

**Comment by dhalperi** [comment]
Merged, thanks. Not sure why this was previously believed hard to fix :/

**Comment by davorbonaci** [comment]
(just saw this, thank you!)

CC: @jasonkuster

**Pull request closed without merging**
