### PR TITLE
[BEAM-2726] Fix typo in programming guide

### PR DESCRIPTION
**Pull request by lukecwik**

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @davorbonaci

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/596/

Jenkins built the site at commit id 66eaf099a53d0500ed817a0653a2b3c3b019aa96 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/280/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by kennknowles** [comment]
Trying again as the failure was inability to verify links. I don't think we have enough links or enough builds to be getting us throttled, though I could be wrong.

**Comment by asfgit** [comment]
MergeBot: Merge: PR 280 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/32/api/python?depth=1&tree=building.. URL: http://mergebot-vm.apache.org/beam-website/280.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/32/api/python?depth=1&tree=building.

**Comment by lukecwik** [comment]
@asfgit merge

**Pull request closed without merging**
