### PR TITLE
[BEAM-2471]EMR DynamoDB example using HadoopIputFormatIO

### PR DESCRIPTION
**Pull request by seshadri-cr**
This effort is to document an example to read from Amazon EMR DynamoDB using HadoopInputFormatIO.
Please let me know if any additional details are required.
JIRA - https://issues.apache.org/jira/browse/BEAM-2471

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/529/

Jenkins built the site at commit id f6d2c5f863d38f4a4486ce4b2d8b4ff4bdccc927 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/258/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/530/

Jenkins built the site at commit id 883d5cf10ab1998774ebb12e450f075e35774043 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/258/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/533/

Jenkins built the site at commit id b5f1e5ce938fa5ec43da8fdc3af8bb25eee7a295 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/258/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/534/

Jenkins built the site at commit id 338eb17460bf92cbee83b0d578fa70be850423b7 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/258/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by seshadri-cr** [comment]
R: @iemejia

**Comment by iemejia** [comment]
LGTM, I will fix some minor issues and merge.

**Comment by iemejia** [comment]
Thanks a lot for your contribution @seshadri-cr. Great job!

**Pull request closed without merging**
