### PR TITLE
Add JingsongLee as committer

### PR DESCRIPTION
**Pull request by JingsongLi**

### CODE REVIEW

**Comment by JingsongLi** [comment]
R: @davorbonaci

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/547/

Jenkins built the site at commit id 277078ac290b9b91378124d491d14b14a758f66c with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/266/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[content/contribute/team/index.html, line 377 at r1](https://reviewable.io:443/reviews/apache/beam-site/266#-KoTFHJnVf1ZSaTYxsxE:-KoTFHJnVf1ZSaTYxsxF:b-dvxz2a) ([raw file](https://github.com/apache/beam-site/blob/277078ac290b9b91378124d491d14b14a758f66c/content/contribute/team/index.html#L377)):*
> ```HTML
>         </tr>
> 
>         <tr>
> ```

Our process for the site is to generate the content separately from the PR, so you should drop this file from the PR.

---

*[src/_beam_team/team.md, line 149 at r1](https://reviewable.io:443/reviews/apache/beam-site/266#-KoTFku0ZyDwl2x42CVE:-KoTFku0ZyDwl2x42CVF:bszb941) ([raw file](https://github.com/apache/beam-site/blob/277078ac290b9b91378124d491d14b14a758f66c/src/_beam_team/team.md#L149)):*
> ```Markdown
>     roles: committer
>     time_zone: "+2"
>   - name: Jingsong Lee
> ```

Just to keep things in alphabetical order, you should be after Aljoscha.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam-site/266)*

**Comment by kennknowles** [comment]
(That was a test of Reviewable - it looks like it doesn't post the comments as a GitHub review)

**Comment by JingsongLi** [comment]
Thanks @kennknowles

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/550/

Jenkins built the site at commit id 1f822219b2373351b69aac28332c0ac64f52b0e1 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/266/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by davorbonaci** [comment]
@asfgit merge

**Pull request closed without merging**
