### PR TITLE
Add Apache headers to website sources

### PR DESCRIPTION
**Pull request by swegner**
This is necessary for importing website sources in apache/beam (See: https://s.apache.org/beam-site-automation)

Getting the formatting right and choosing which files need license headers was done byexamining how other Apache projects add license headers for various file types. In particular, [Apache Zepplin](https://github.com/apache/zeppelin/tree/master/docs) seemed to be a good example, and in other cases doing a [search across Apache GitHub](https://github.com/search?utf8=%E2%9C%93&q=%22See+the+License+for+the+specific+language+governing+permissions%22+user%3Aapache+extension%3Ayml&type=Code&ref=advsearch&l=&l=).

### CODE REVIEW

**Comment by kennknowles** [comment]
http://apache-beam-website-pull-requests.storage.googleapis.com/481/index.html

**Comment by swegner** [comment]
Ah, thanks for the staging link. It looks totally broken, and I forgot to test this locally.  Hold off on reviewing for now; I'll fix it up and let you know.

**Comment by swegner** [comment]
I believe this is now ready for review: [staging link](http://apache-beam-website-pull-requests.storage.googleapis.com/481/index.html). I clicked around various pages where I thought things could be broken and didn't find anything. I also checked the JS console, which does have a couple errors but the currently deployed site also has them, so these aren't a regression.

@kennknowles PTAL

**Comment by kennknowles** [comment]
Yup, clicked around a bit without hitting anything wonky.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by swegner** [comment]
@asfgit merge

**Pull request closed without merging**
