### PR TITLE
Add Hive (HCatalog) to the list of available I/O transforms

### PR DESCRIPTION
**Pull request by iemejia**

### CODE REVIEW

**Comment by iemejia** [comment]
R: @davorbonaci or @jbonofre

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/525/

Jenkins built the site at commit id 993d2c4ac6fe9c564d9c0e3166298c6f4edce099 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/256/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by davorbonaci** [comment]
LGTM. Please self-merge.

retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/526/

Jenkins built the site at commit id 993d2c4ac6fe9c564d9c0e3166298c6f4edce099 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/256/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Pull request merged**
