### PR TITLE
parallelise test

### PR DESCRIPTION
**Pull request by taromurao**
Told HTMLProofer to do internal file checks in parallel.

### CODE REVIEW

**Comment by taromurao** [comment]
@melap I just pulled the most recent master, picked up my changes in my previous parallelise-test branch and created this new PR in order to clear merge problems.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by melap** [comment]
@jasonkuster is looking into this -- seems there is still some sort of issue with the auto-merging.

**Comment by melap** [comment]
I went ahead and merged this manually as there is still some investigation to find the robot bug and this PR is so useful. Thank you @taromurao !

**Comment by taromurao** [comment]
@melap Thanks for notifying. I am glad to hear. On the other hand, I am sorry that the bot failed fulfilling his duty...

**Pull request closed without merging**
