### PR TITLE
add MingminXu(mingmxu) as committer

### PR DESCRIPTION
**Pull request by mingmxu**
R: @davorbonaci

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/607/

Jenkins built the site at commit id 4d9289c14be2dedc006b0b0d43685158b77e9036 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/285/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by tgroh** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by tgroh** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by kennknowles** [comment]
retest this please

**Comment by XuMingmin** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/632/

Jenkins built the site at commit id 4d9289c14be2dedc006b0b0d43685158b77e9036 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/285/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
@jasonkuster it looks like mergebot pushed a couple merge commits, but not to `asf-site`.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/636/

Jenkins built the site at commit id 4d9289c14be2dedc006b0b0d43685158b77e9036 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/285/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by XuMingmin** [comment]
Seems this is not the only case, 288/281 also fails.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/637/

Jenkins built the site at commit id 504f135a13f77a5a9152b5f756f6ef36fb945f13 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/285/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by reuvenlax** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: User reuvenlax not a committer on beam-website or not registered in gitbox.apache.org; access denied.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/663/

Jenkins built the site at commit id 504f135a13f77a5a9152b5f756f6ef36fb945f13 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/285/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/664/

Jenkins built the site at commit id 75dee9f1529e7e33ae063193c8f265a3fffc22be with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/285/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Pull request closed without merging**
