### PR TITLE
Fix broken JIRA component links

### PR DESCRIPTION
**Pull request by melap**
All the JIRA component links went 404 in the last few days. Guessing it may be related to the major update to JIRA on Jan 14. (https://twitter.com/infrabot)

### CODE REVIEW

**Comment by melap** [comment]
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/375/index.html

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 375 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/375.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
@asfgit merge

**Pull request merged**
