### PR TITLE
[MINOR] scrollable dropdown menu

### PR DESCRIPTION
**Pull request by vectorijk**
support for scrollable dropdown menu

image

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/662/

Jenkins built the site at commit id ce98c289953001f44172c6b088528143ae229a4a with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/308/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by reuvenlax** [comment]
R: @melap

**Comment by vectorijk** [comment]
@melap Since you will improving the navigation story, should I close this PR?
Eventually, I think we should support scrollable pulldown menu. It is too long to see all items.

**Comment by melap** [comment]
no, I agree, I think it's very useful and fixes a problem for small windows until future improvements are finished. my only concern is that it does make things less discoverable if looking at the menu in a full-size browser window , as all items are not visible at once anymore. so I was wondering if there's a way to only do the scrollbar if the window is smaller than the menu pulldown. maybe there is no way, I am not sure.

**Comment by vectorijk** [comment]
#332 solved. I would close this.

**Pull request closed without merging**
