### PR TITLE
[BEAM-3338] Add SDK specific pages to SDK left nav

### PR DESCRIPTION
**Pull request by melap**
- Improve discoverability of SDK specific pages (most notably some the Python specific pages that users have trouble finding)
- Make all left nav titles consistent (sentence case) (will be doing this for all left navs)

### CODE REVIEW

**Comment by melap** [comment]
retest this please

**Comment by melap** [comment]
Staged at http://apache-beam-website-pull-requests.storage.googleapis.com/364/documentation/sdks/python/index.html

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 364 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/364.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
