### PR TITLE
Update keywords from BeamSqlParserImplConstants

### PR DESCRIPTION
**Pull request by apilloud**
@kennknowles

### CODE REVIEW

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by apilloud** [comment]
Rebased

**Comment by apilloud** [comment]
`gpg: keyserver receive failed: unknown pubkey algorithm`

**Comment by apilloud** [comment]
retest this please

**Comment by apilloud** [comment]
`gpg: keyserver receive failed: unknown pubkey algorithm`

**Comment by apilloud** [comment]
retest this please

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 480 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/256/api/python?depth=1&tree=building.. URL: http://mergebot-vm2.apache.org:8080/beam-website/480.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/256/api/python?depth=1&tree=building.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 480 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm2.apache.org:8080/beam-website/480.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Pull request merged**
