### PR TITLE
[BEAM-3162] Add IBM Streams Runner to compatability matrix

### PR DESCRIPTION
**Pull request by pgerv12**

### CODE REVIEW

**Comment by kennknowles** [comment]
Jenkins staged it at http://apache-beam-website-pull-requests.storage.googleapis.com/347/documentation/runners/capability-matrix/index.html but the comment appears broken at the moment.

**Comment by kennknowles** [comment]
@melap LGTM if it LGTY

This is an interesting addition to the discussion of a more user-oriented and useful runner comparison for https://issues.apache.org/jira/browse/BEAM-2888.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 347 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm.apache.org/beam-website/347.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 347 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/347.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
Hmm, seems to be Jenkins troubles.

**Comment by melap** [comment]
@asfgit merge

**Pull request merged**
