### PR TITLE
[BEAM-500] Finished skeleton of new website layout

### PR DESCRIPTION
**Pull request by francesperry**
Bunch of website layout changes to follow up on devindonnelly's pr/25
-  got 'rake test' passing again (modulo struggles with files that have changed location, which tries to find them on the live site) and added instructions to README.md
- merged two conflicting organization strategies ('_pages' and 'docs/{use, learn, contribute}' into '{use, learn, contribute, blog, project}'
- created placeholder pages for the remaining things in https://goo.gl/cgFUHf and filed jira issues to fill them in
- standardized multi-word urls/files to use - not _
- added jekyll-redirect-from and redirects for modified links (don't work locally though, since they try to redirect to the live site)
- removed the disclaimer/alert, since it made tests mad and has been replaced by jira links for unwritten content anyway
- temporarily removed the nanthrax link, since it's down (causing test issues)

Left all the content/ junk out of this CL. Will regenerate it during the final merge.

Reviewers: @evilsoapbox @dhalperi

### CODE REVIEW

**Comment by evilsoapbox** [comment]
Overall LGTM. Noticed a few things unrelated to this PR which I will open JIRAs for:

- Some pages are missing page titles which is slightly confusing (JIRA page as an example)
- Runner pages have a title missing 'Apache' (/learn/runners/flink/) but do have Apache in the nav

**Comment by francesperry** [comment]
cc: @jbonofre FYI, hope this will merge ok with yours!

**Comment by francesperry** [comment]
@evilsoapbox Any thoughts on the test failures? It's pretty clearly some confusion around the live site not yet having the pages I added. Worst case, I could submit and immediately check it's gone green.

**Comment by francesperry** [comment]
@evilsoapbox fixed those, thanks!

**Comment by evilsoapbox** [comment]
@francesperry After some tinkering, you can simulate a local build by changing the following in the `_config.yml` file:

    # the base hostname & protocol for your site
    #url: "http://beam.incubator.apache.org"

Of course, this is a hack but it will build the content without the FQDN - when rake it run all paths will be relative and it seems to work OK:

```
(venv) ➜  incubator-beam-site git:(layout-beam-500) ✗ rake test
bundle exec jekyll build
Configuration file: /Users/jamesmalone/t4/fjp/incubator-beam-site/_config.yml
            Source: /Users/jamesmalone/t4/fjp/incubator-beam-site
       Destination: content
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 3.906 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["./content"] on *.html... 


Checking 100 external links...
Ran on 52 files!


HTML-Proofer finished successfully.
(venv) ➜  incubator-beam-site git:(layout-beam-500) ✗ 
```

**Comment by jbonofre** [comment]
No worries. I will rebase and propose a PR based on this one.

**Pull request closed without merging**
