### PR TITLE
Add yaml docs to beam reference documentation website.

### PR DESCRIPTION
**Pull request by robertwb**
This was generated with `python -m apache_beam.yaml.generate_yaml_docs`.

(Adding this to the beam release process is at https://github.com/apache/beam/pull/30741.)

### CODE REVIEW

**Comment by robertwb** [comment]
R: @Abacn

**Review by brucearctor — APPROVED** [review]
LGTM

**Comment by brucearctor** [comment]
I am assuming since auto-generated, what is generated is what we want ...  Didn't verify the `index.html` page.

**Comment by robertwb** [comment]
Thanks. 

Yeah, this is mostly a question of placement. (The html generation has been reviewed in previous PRs.)

**Pull request merged**
