### PR TITLE
Add link to design docs and template to the contribution guide.

### PR DESCRIPTION
**Pull request by lukecwik**
Provide links to design docs and template.

### CODE REVIEW

**Comment by lukecwik** [comment]
The link is labelled `examples` and is pointing to a place where a person can look at some past design docs. It says nothing about being binding / exhaustive. I don't think adding legalese around the docs will be helpful for the contribution guide.

Also, I agree that the examples link could point to a page with links/abstracts once it exists.

**Comment by kennknowles** [comment]
Fair enough. LGTM

**Comment by lukecwik** [comment]
Checked staged website at http://apache-beam-website-pull-requests.storage.googleapis.com/454/index.html, doesn't look like any formatting issues.

**Comment by lukecwik** [comment]
@asfgit merge

**Pull request merged**
