### PR TITLE
documentation changes for 2.2.0-RC2

### PR DESCRIPTION
**Pull request by reuvenlax**
Documentation changes for 2.2.0

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/746/

**Comment by reuvenlax** [comment]
@melap does this look ok?

**Comment by melap** [comment]
retest this please

**Comment by melap** [comment]
hmm, there are a bunch of broken links now on pages pointing to the javadoc. were they code changes where the pages should be updated, or javadoc generation issues?

**Comment by reuvenlax** [comment]
@melap Where are the broken links?

**Comment by melap** [comment]
they're all the bottom of https://builds.apache.org/job/beam_PreCommit_Website_Test/739/console 
short version after more digging: I think this PR is fine, but there are multiple broken things I've made note of to be fixed, unrelated to this PR.

long version: my bad -- it's actually complaining about pydoc. 2 of the links work on the staged site, so I don't know why they failed during testing. the other is validly broken due to a hard coded site URL (unrelated to PR). 2 are due to the gitbox move, also unrelated to this PR.

**Comment by reuvenlax** [comment]
@melap Ok, so you're saying we should merge this PR then?

**Comment by melap** [comment]
@reuvenlax yeah, I'd say go ahead and merge when the release is ready. the two pipeline options links are due to a pydoc URL change, and I believe I know the cause. I'll follow behind with a PR to fix those two links once the new pydoc structure is live. the other link issues are fixed in pending or merged PRs.

**Comment by melap** [comment]
suspected fixes to direct and Dataflow runner pages in #357

**Comment by reuvenlax** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: User reuvenlax not a committer on beam-website or not registered in gitbox.apache.org; access denied.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
retest this please

**Comment by reuvenlax** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 337 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/maven-release-jf/api/python?tree=jobs%5Bname%2Ccolor%5D.. URL: http://mergebot-vm.apache.org/beam-website/337.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/maven-release-jf/api/python?tree=jobs%5Bname%2Ccolor%5D.

**Comment by reuvenlax** [comment]
@asfgit merge

**Pull request merged**
