### PR TITLE
[BEAM-5667] remove gradle files from website

### PR DESCRIPTION
**Pull request by yifanzou**
*Please* add a meaningful description for your change here.

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/PULL_REQUEST_NUMBER/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by yifanzou** [comment]
+R: @swegner

**Comment by swegner** [comment]
LGTM

**Comment by swegner** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Pull request merged**
