### PR TITLE
Spelling correction

### PR DESCRIPTION
**Pull request by coheigea**

### CODE REVIEW

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by coheigea** [comment]
Looks like the Jenkins job failed, can it be re-tested?

**Comment by pabloem** [comment]
@asfgit merge

**Comment by pabloem** [comment]
retest this please

**Comment by pabloem** [comment]
you can use that "retest this please" phrase to trigger jenkins to retest the PR

**Comment by kennknowles** [comment]
@asfgit merge

**Pull request closed without merging**
