### PR TITLE
Website changes for 2.4.0.

### PR DESCRIPTION
**Pull request by robertwb**

### CODE REVIEW

**Comment by melap** [comment]
Not sure if the actual release download link will be added as part of this PR or another one, but wanted to bring attention to this JIRA I found while triaging website JIRAs yesterday. Seems we need to add signature file/hashes for each release to the downloads page as part of the release process?
https://issues.apache.org/jira/browse/BEAM-3717

**Comment by melap** [comment]
#399 configures better timeouts for link checking, which may help. we've been getting a lot of error code 0 timeouts on valid links lately.

**Comment by robertwb** [comment]
Added (BEAM-3717 conformant) download link. The release is out, this should be ready to merge.

**Comment by robertwb** [comment]
@asfgit merge

**Pull request closed without merging**
