### PR TITLE
[BEAM-3117] Fix misleading reference to bundles and windows

### PR DESCRIPTION
**Pull request by melap**
Reword misleading paragraph that seems to equate bundles with windows.

### CODE REVIEW

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Mergebot couldn't fetch the list of authorized users from Apache; check people.apache.org and gitbox.apache.org for downtime.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Merge was not successful. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Merge was not successful. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 378 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/maven-box/job/maven-changelog-plugin/api/python?tree=jobs%5Bname%2Ccolor%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f400ec7acd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)).. URL: http://mergebot-vm.apache.org/beam-website/378.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/maven-box/job/maven-changelog-plugin/api/python?tree=jobs%5Bname%2Ccolor%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f400ec7acd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)).

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 378 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/378.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Pull request merged**
