### PR TITLE
[BEAM-2664] Make latest stable version more visible

### PR DESCRIPTION
**Pull request by melap**
This PR contains:
- Add new download buttons that contain the latest version on the top and bottom of the homepage
- Add note at the top of the downloads page that contains the latest version
- A few text changes on the downloads page: central repository/downloading sections
- A few line length cleanups

### CODE REVIEW

**Comment by melap** [comment]
retest this please

**Comment by melap** [comment]
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/367/index.html

**Comment by melap** [comment]
retest this please

**Comment by lukecwik** [comment]
@asfgit merge

**Pull request closed without merging**
