### PR TITLE
[BEAM-4771]Rename RowType to Schema in SQL walkthrough

### PR DESCRIPTION
**Pull request by akedin**
Update SQL walkthrough to reflect `RowType`->`Schema` rename

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/495/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by akedin** [comment]
R: @apilloud @melap

**Comment by akedin** [comment]
ping

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 495 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/277/api/python?depth=1&tree=building.. URL: http://mergebot-vm2.apache.org:8080/beam-website/495.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/277/api/python?depth=1&tree=building.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
