### PR TITLE
Adds Jenkins jobs definitions pointer to #building--testing

### PR DESCRIPTION
**Pull request by ThatRfernand**
As discussed in dev[1], adding additional information to the contributors guide.

Also took the opportunity to clean up whitespaces and minor things.

[1] https://lists.apache.org/thread.html/e78fbfc2161e061066f85f2ee84773e5f422edf7bf6905185b801ac5@%3Cdev.beam.apache.org%3E

http://apache-beam-website-pull-requests.storage.googleapis.com/535/index.html

### CODE REVIEW

**Comment by ThatRfernand** [comment]
R: @tweise , @melap

**Comment by ThatRfernand** [comment]
retest this please

**Comment by tweise** [comment]
Please mention `./gradlew projects` and `./gradlew tasks --all` in https://beam.apache.org/contribute/#building--testing

**Comment by tweise** [comment]
@asfgit merge

**Pull request merged**
