### PR TITLE
[BEAM-1896] Add "In-Progress" info to the Built-in I/O Transforms page

### PR DESCRIPTION
**Pull request by ssisk**
Also added the Apache Hadoop InputFormat to the existing transforms list.

cc @melap

### CODE REVIEW

**Comment by ssisk** [comment]
The website test failed with weird errors like:
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apache/beam-site.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:806)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1070)

I don't believe that's caused by my changes

**Comment by melap** [comment]
Might be good to have the header row in bold. Text LGTM.

**Comment by ssisk** [comment]
thanks! that's helpful. I updated to have the header row in bold.

**Comment by melap** [comment]
LGTM

**Pull request closed without merging**
