### PR TITLE
Add myself as a committer

### PR DESCRIPTION
**Pull request by echauchot**
R: @iemejia

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by echauchot** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 348 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/348.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by echauchot** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 348 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/348.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Pull request closed without merging**
