### PR TITLE
Quickstart: suggest using nightly build temporarily

### PR DESCRIPTION
**Pull request by davorbonaci**
R:  @kennknowles
CC: @francesperry, @dhalperi

Please review, but don't merge.

### CODE REVIEW

**Comment by davorbonaci** [comment]
This should work after @peihe's apache/incubator-beam#1407. Ready for merging, as soon as someone LGTMs.

**Comment by jasonkuster** [comment]
LGTM

**Comment by kennknowles** [comment]
LGTM

**Comment by kennknowles** [comment]
We should merge https://github.com/apache/incubator-beam/pull/1344 as-is and iterate so the instructions can be up-to-date with the examples.

**Pull request closed without merging**
