### PR TITLE
Update nexmark support matrix for timer and state APIs

### PR DESCRIPTION
**Pull request by echauchot**

### CODE REVIEW

**Comment by iemejia** [comment]
@asfgit merge

**Comment by melap** [comment]
OK, it should be processing commands again.

**Comment by asfgit** [comment]
MergeBot: Merge: PR 409 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm2.apache.org:8080/beam-website/409.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
