### PR TITLE
Add instructions about how to sign and hash python wheels

### PR DESCRIPTION
**Pull request by boyuanzz**
r: @charlesccychen

### CODE REVIEW

**Comment by charlesccychen** [comment]
Thanks! This LGTM.

**Comment by charlesccychen** [comment]
Retest this please

**Comment by boyuanzz** [comment]
This PR is ready to merge. @charlesccychen

**Comment by charlesccychen** [comment]
Thanks @boyuanzz!  Sorry I missed this.  This LGTM.

**Comment by charlesccychen** [comment]
@asfgit merge

**Pull request closed without merging**
