### PR TITLE
Update the create table doc

### PR DESCRIPTION
**Pull request by apilloud**
This updates the CREATE TABLE doc and simplifies the SQL page leveling.

http://apache-beam-website-pull-requests.storage.googleapis.com/482/index.html

### CODE REVIEW

**Comment by apilloud** [comment]
`keyserver receive failed: unknown pubkey algorithm`

**Comment by apilloud** [comment]
retest this please

**Comment by apilloud** [comment]
`gpg: keyserver receive failed: keyserver error`

**Comment by apilloud** [comment]
retest this please

**Comment by apilloud** [comment]
`gpg: keyserver receive failed: unknown pubkey algorithm`

**Comment by apilloud** [comment]
retest this please

**Comment by apilloud** [comment]
retest this please

**Comment by apilloud** [comment]
@kennknowles The "Test website" job seems impossibly broken. It is failing because pages that I add in this PR don't exist.

**Comment by apilloud** [comment]
I've dropped the commit to relocate the pages up a level so I can get the actual doc change in.

**Comment by kennknowles** [comment]
It is a known problem with the check, I think :-/

**Comment by kennknowles** [comment]
Well OTOH I have suceeded in the past.

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
I think it is valuable to have a separate Data Sources section to raise visibility of different connectors. I don't think they should all be in the CREATE TABLE doc. Let's do that as a followup. If the pre-merge check succeeds I want this to go in ASAP. It is so nice!

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by asfgit** [comment]
MergeBot: Merge: PR 482 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm2.apache.org:8080/beam-website/482.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Pull request merged**
