### PR TITLE
[BEAM-2126] Add JStorm runner to ongoing projects.

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @kennknowles

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/577/

Jenkins built the site at commit id fb4a8bc3d5a95d476e442e8884c21188e1d25a7d with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/277/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
Please edit the `src` directory. The `content` directory is the checked-in output of the build.

**Comment by peihe** [comment]
updated

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/585/

Jenkins built the site at commit id 2c10fe4f479a10c81c52b0645743f05cbbb53766 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/277/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
Great. LGTM.

**Comment by kennknowles** [comment]
@asfgit merge

**Pull request closed without merging**
