### PR TITLE
[BEAM-2078] add BeamSQL feature branch in site

### PR DESCRIPTION
**Pull request by mingmxu**

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
Jenkins: retest this please

**Comment by XuMingmin** [comment]
@davorbonaci checked _https://beam.apache.org/contribute/work-in-progress/_, seems as it's not in the page. Could you have a check?

**Comment by kennknowles** [comment]
This PR edited the generated content, not the source. Try another PR against https://github.com/apache/beam-site/blob/asf-site/src/contribute/work-in-progress.md.

**Comment by XuMingmin** [comment]
Thanks @kennknowles to figure out the problem, will create a new one soon.

**Pull request merged**
