### PR TITLE
Publish 2.5.0 release

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by swegner** [comment]
R: @ThatRfernand

**Comment by swegner** [comment]
Previous test failures are for 2.5.0 release files which are now available.

**Comment by swegner** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by jbonofre** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by aaltay** [comment]
Failed with link errors, but I can access those links myself.

- ./.testcontent/get-started/downloads/index.html
  *  External link https://dist.apache.org/repos/dist/release/beam/2.5.0/apache-beam-2.5.0-source-release.zip failed: 404 No error
  *  External link https://dist.apache.org/repos/dist/release/beam/2.5.0/apache-beam-2.5.0-source-release.zip.asc failed: 404 No error
  *  External link https://dist.apache.org/repos/dist/release/beam/2.5.0/apache-beam-2.5.0-source-release.zip.sha512 failed: 404 No error
rake aborted!

**Comment by aaltay** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by aaltay** [comment]
I know @jbonofre is traveling. I propose merging this manually (I can do) and doing another follow up PR to fix the issues (I can do). Any objections?

**Comment by lukecwik** [comment]
SGTM

**Comment by ThatRfernand** [comment]
+1

**Comment by aaltay** [comment]
Follow up PR: https://github.com/apache/beam-site/pull/478

**Pull request closed without merging**
