### PR TITLE
[DO NOT MERGE] add pydoc for release-2.18.0(dba0c68) generated in python 3.7

### PR DESCRIPTION
**Pull request by yoshikiobata**
This PR is intended to review pydoc generated in python 3.7 and **DO NOT MERGE**
Once reviewers confirmed that the docs are all right, this PR will be closed.

Docs generated in python 3 review process is assumed as follows:

1. Create PR for apache/beam-site about docs generated by scripts
(hereinafter called PR1)
    PR1 is intended only to review docs, so it must not to be merged.
2. create PR for apache/beam about modification to docs-generating
scripts (hereinafter called PR2)
3. PR1 and PR2 are reviewed and confirmed to be OK, close PR1.
4. Merge PR2.

Modification to scripts is here: https://github.com/apache/beam/pull/10141

### CODE REVIEW

**Comment by udim** [comment]
LGTM, thanks!

**Comment by yoshikiobata** [comment]
add documents for 2.19.0 according to update of scripts in https://github.com/apache/beam/pull/10141

**Comment by yoshikiobata** [comment]
@tvalentyn @udim @soyrice
I would appreciate if you review this:
https://github.com/apache/beam-site/tree/bc0304ff55a23a984f108cf3355fc5c5fadb7148/pydoc/2.19.0_generated_in_py3

and @udim sorry for taking up your time again.

**Comment by tvalentyn** [comment]
Run WebsiteRun Website_Stage_GCS PreCommit

**Comment by tvalentyn** [comment]
Run Website_Stage_GCS PreCommit

**Comment by udim** [comment]
This looks good. I left a comment here: https://github.com/apache/beam/pull/10141#pullrequestreview-348836305

**Comment by yoshikiobata** [comment]
@udim Thank you for reviewing. I've fixed docstring you left comment.

**Comment by yoshikiobata** [comment]
https://github.com/apache/beam/pull/10141 was merged, I close this.
Thank you all for your help!

**Pull request closed without merging**
