### PR TITLE
Update Mapreduce capability matrix when/how entries

### PR DESCRIPTION
**Pull request by melap**
Update to no for page consistency, as it's a batch-only runner
R: @peihe @kennknowles

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/710/

Jenkins built the site at commit id dfc91955334028ab861b4766799688a6d5709f4d with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/324/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
Yea, this is much clearer to users. It sends a really good signal that this is a batch-only runner.

**Comment by kennknowles** [comment]
Can you follow this up or push another commit that updates the "How" as well? Those are also not relevant for batch only.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/713/

Jenkins built the site at commit id d9e10e65880ffb3b936cfe38e6d75d3f940e1f34 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/324/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by melap** [comment]
Sure, just updated this with changes to "How" also.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by kennknowles** [comment]
Failure to merge was an external link timing out (flink.apache.org). Kicking again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by tgroh** [comment]
@asfgit merge

**Pull request closed without merging**
