### PR TITLE
Update release date for 2.2.0 release

### PR DESCRIPTION
**Pull request by aaltay**
R: @reuvenlax

### CODE REVIEW

**Comment by reuvenlax** [comment]
lgtm

**Comment by aaltay** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 360 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm.apache.org/beam-website/360.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
