### PR TITLE
Add pointers to 0.3.0-incubating release artifacts

### PR DESCRIPTION
**Pull request by aljoscha**

### CODE REVIEW

**Comment by dhalperi** [comment]
There are 3 generated packages we should add to the Javadoc exclusions:

* org.apache.beam.sdk.microbenchmarks.coders.generated	
* org.apache.beam.sdk.microbenchmarks.transforms.generated
* org.openjdk.jmh.infra.generated

There are all coming from the microbenchmarks code, somehow. They can perhaps be excluded in those modules' pom files. I'm not certain yet, but I think adding them manually to the exclusion list will do for now.

**Comment by aljoscha** [comment]
Ok, I'll add them and rebuild the javadocs when the release vote is over. (In case more pops up.)

**Comment by dhalperi** [comment]
> when the release vote is over. (In case more pops up.)

+1. Just going to be dumping various comments in here :)

**Comment by dhalperi** [comment]
What version of the JDK are you using? I see a 404 `dejavu.css` in my `jekyll` server, which was maybe [fixed with the relatively old 8u20](https://bugs.openjdk.java.net/browse/JDK-8093199)?

**Comment by aljoscha** [comment]
I have:
```
~ $ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by davorbonaci** [comment]
retest this please

(triggering Jenkins)

**Comment by aljoscha** [comment]
@dhalperi I added the 3 exclusions and rebuilt the Javadoc.

**Comment by dhalperi** [comment]
LGTM! I was able to browse the staged website  (with many selective additions of `/index.html`) and it looks great.

**Pull request closed without merging**
