### PR TITLE
Add a pull request template with staged URL

### PR DESCRIPTION
**Pull request by kennknowles**
In the absence of a comment from Jenkins, and potentially highlighted more prominently, just add the staging URL to every PRs description

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @jkff

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by kennknowles** [comment]
Oh, this doesn't change content so it cannot work. Got it.

**Pull request merged**
