### PR TITLE
Add Reuven Lax as PMC member.

### PR DESCRIPTION
**Pull request by reuvenlax**

### CODE REVIEW

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 346 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/83/api/python?depth=1&tree=building.. URL: http://mergebot-vm.apache.org/beam-website/346.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/83/api/python?depth=1&tree=building.

**Comment by reuvenlax** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: User reuvenlax not a committer on beam-website or not registered in gitbox.apache.org; access denied.

**Comment by aaltay** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by aaltay** [comment]
@jasonkuster do you know why we cannot merge this change with merge bot?

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 346 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm.apache.org/beam-website/346.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 346 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/346.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
