### PR TITLE
Fixes broken links for downloading source releases.

### PR DESCRIPTION
**Pull request by chamikaramj**

### CODE REVIEW

**Comment by chamikaramj** [comment]
Thanks. Can you also merge. Looks like I don't have write access to this repository.

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
@asfbot merge

**Comment by chamikaramj** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by aaltay** [comment]
@asfgit merge

**Comment by chamikaramj** [comment]
@asfgit merge

**Pull request merged**
