### PR TITLE
Update beam-site for release 2.6.0

### PR DESCRIPTION
**Pull request by pabloem**
Uploading all documentation for 2.6.0 release.

### CODE REVIEW

**Comment by pabloem** [comment]
Retest this please

**Comment by pabloem** [comment]
Retest this please

**Comment by pabloem** [comment]
Retest this please

**Comment by aijamalnk** [comment]
Retest this please

**Comment by pabloem** [comment]
Retest this please

**Comment by pabloem** [comment]
r: @melap

**Comment by pabloem** [comment]
@asfgit merge

**Pull request closed without merging**
