### PR TITLE
Update instructions to run linter.

### PR DESCRIPTION
**Pull request by tvalentyn**
Changes to tox.ini were done in https://github.com/apache/beam/pull/4877.

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @udim

**Comment by melap** [comment]
#411 and #415 both also make this change,  and the changed line is removed in #414
what is the long term strategy here? from the comments in #411 it sounded like this change will be obsoleted by #414 so #411 was closed

**Comment by melap** [comment]
sorry, removed in #412 (not 415)

**Comment by tvalentyn** [comment]
Thanks, looks like with https://github.com/apache/beam-site/pull/412/ this change is no longer needed.

**Comment by melap** [comment]
A fair point, I will merge this

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
