### PR TITLE
Capabilities Matrix: Stateful processing support in Apex Runner

### PR DESCRIPTION
**Pull request by tweise**

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by aaltay** [comment]
Any updates?

**Comment by tweise** [comment]
@aaltay @kennknowles can one of you please merge the PR?

**Comment by aaltay** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 351 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/93/api/python?depth=1&tree=building.. URL: http://mergebot-vm.apache.org/beam-website/351.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/93/api/python?depth=1&tree=building.

**Pull request closed without merging**
