### PR TITLE
Update Gearpump runner related pages

### PR DESCRIPTION
**Pull request by huafengw**
Gearpump runner was merged into Beam's master recently. The remaining part is the quick start part but right now GP runner only has a snapshot version. I'll do that once Beam 2.2.0 comes out.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/643/

Jenkins built the site at commit id 700cea3533c6cc210a885ec1a173324c44411a08 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/298/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by huafengw** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
R: @melap to double-check. Are there any other places that you can think of that need update?

**Comment by melap** [comment]
The only other place I can think of right now (besides the quickstart mentioned above) is the WordCount walkthrough, as there are also runner specific command lines in there. But, that may need to wait and be updated when the quickstart is updated.

**Comment by huafengw** [comment]
Hi @melap, the WordCount walkthrough is just like the quickstart, so I'll update these pages in another pull request once 2.2.0 come out, is that OK?

**Comment by melap** [comment]
Thanks @huafengw  - I agree it makes sense to update it whenever you update the quickstart

**Comment by manuzhang** [comment]
Any more comments for this PR ? @melap @kennknowles

**Comment by melap** [comment]
Nope, nothing else, looks fine to me

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by kennknowles** [comment]
It is a true dead link due to changes in the Javadoc (links to classes that are gone).

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/679/

Jenkins built the site at commit id 7b3427696e15929167893e735dfb955d13e8ef1a with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/298/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by kennknowles** [comment]
The failures this time do not appear to be legitimate, so hopefully this can merge.

**Pull request merged**
