### PR TITLE
Added new design documents

### PR DESCRIPTION
**Pull request by aromanenko-dev**
Added new 3 design documents for Beam SQL

@echauchot @iemejia Please, take a look

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by aromanenko-dev** [comment]
@jbonofre @echauchot could you take a look?

**Comment by echauchot** [comment]
@aromanenko-dev sure

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
@asfgit merge

**Pull request closed without merging**
