### PR TITLE
Regenerate to post PCollection blog post

### PR DESCRIPTION
**Pull request by james-malone**

### CODE REVIEW

**Comment by davorbonaci** [comment]
Do we want to move forward? Perhaps, Robert can review?

**Comment by robertwb** [comment]
+1 to getting this out. Should we re-generate so that it doesn't start out as 5 days old?

**Comment by evilsoapbox** [comment]
What do we want for the new post date, today?

**Comment by robertwb** [comment]
Today makes sense to me. Other than that, LGTM.

**Comment by francesperry** [comment]
LGTM too!

**Pull request merged**
