### PR TITLE
[BEAM-5124] DSL Euphoria documentation update

### PR DESCRIPTION
**Pull request by VaclavPlajt**
Euphoria documentation was largely rewritten.

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/540/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.
@jbonofre

### CODE REVIEW

**Comment by pabloem** [comment]
You can comment "retest this please" in the pull request, and that should
retrigger the tests

**Comment by VaclavPlajt** [comment]
retest this please

**Comment by pabloem** [comment]
Retest this please

**Comment by pabloem** [comment]
Apache Builds had been having trouble, and also the dead links tests are very flaky. We may need to retest a number of time.

**Comment by VaclavPlajt** [comment]
Ok, I will try it several times Thanks for your help @pabloem :-)

**Comment by VaclavPlajt** [comment]
Retest this please

**Comment by pabloem** [comment]
Retest this please

**Comment by VaclavPlajt** [comment]
Retest this please

**Comment by pabloem** [comment]
Gladly we got it to work now. Now we just need to wait for a reviewer

**Comment by melap** [comment]
R: @jbonofre

**Comment by VaclavPlajt** [comment]
Closing. Newer version of documentation is a part of https://github.com/apache/beam/pull/6601

**Pull request closed without merging**
