### PR TITLE
Fix typo in becoming-a-committer docs

### PR DESCRIPTION
**Pull request by swegner**
R: @kennknowles

### CODE REVIEW

**Comment by kennknowles** [comment]
Edited your branch. WDYT? Squash in my commit? :-)

**Comment by swegner** [comment]
LGTM; Looks like some link has gone dead; I'll submit a separate PR and rebase this on top

**Comment by kennknowles** [comment]
Oh, what the. `DoFnTester` is deprecated because it never really worked.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by swegner** [comment]
Pretty-please @asfgit merge :wink: 

Does mergebot need to be kicked? @kennknowles @jasonkuster

**Comment by melap** [comment]
It does appear something is awry, I can't even connect to the mergebot status page

**Comment by swegner** [comment]
FYI, this is rebased on-top of PR #448

**Comment by jasonkuster** [comment]
@asfgit merge

**Pull request closed without merging**
