### PR TITLE
Fix Apex Runner instructions for execution on YARN

### PR DESCRIPTION
**Pull request by tweise**
http://apache-beam-website-pull-requests.storage.googleapis.com/524/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by tweise** [comment]
@pabloem can you take a look please?

**Comment by pabloem** [comment]
Looking

**Comment by pabloem** [comment]
This LGTM. Thanks Thomas!

**Comment by pabloem** [comment]
@asfgit merge

**Pull request closed without merging**
