### PR TITLE
Add Jenkins job definitions for existing projects using Jenkins DSL

### PR DESCRIPTION
**Pull request by davorbonaci**
R: @dhalperi @jasonkuster 

It works beautifully for the "test" project. It doesn't work for the "stage" project due to jenkinsci/ghprb-plugin#417.

### CODE REVIEW

**Comment by davorbonaci** [comment]
@dhalperi, @jasonkuster, I found a way to solve the problem. I think this should be ready to go. (Of course, the final test can only be done after merging.) So happy to have this completed!

**Comment by davorbonaci** [comment]
After 39 attempts, it is all working now!

**Comment by jasonkuster** [comment]
LGTM. This is going to be an awesome improvement.

**Comment by davorbonaci** [comment]
Thanks! Merging.

**Pull request merged**
