### PR TITLE
Add SQL area to ongoing projects

### PR DESCRIPTION
**Pull request by kennknowles**

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @tgroh

**Comment by kennknowles** [comment]
Also @robertwb who prompted it and @akedin @XuMingmin @xumingming @apilloud who have been committing here. I'm volunteering to be point of contact.

**Comment by apilloud** [comment]
LGTM

**Comment by akedin** [comment]
lgtm

**Comment by kennknowles** [comment]
Per new policy, thanks for the reviews!

**Comment by kennknowles** [comment]
@asfgit merge

**Pull request closed without merging**
