### PR TITLE
[BEAM-4361] Document usage of HBase TableSnapshotInputFormat

### PR DESCRIPTION
**Pull request by timrobertson100**
Provides documentation of how to use the `TableSnapshotInputFormat` for reading HBase snapshots.  This is a common read pattern in HBase especially when one wishes to keep load off a cluster (bypasses region servers so no GC etc) or when doing analysis on historical data which is held as snapshots.

CC @iemejia @aaltay - perhaps one of you could review this please?

### CODE REVIEW

**Comment by timrobertson100** [comment]
Retest this please

**Comment by timrobertson100** [comment]
Broken build is due to a dead external link which is not related to this PR. Another PR addresses that issue.

**Comment by timrobertson100** [comment]
Rebased as requested @iemejia

**Comment by iemejia** [comment]
@asfgit merge

**Comment by iemejia** [comment]
LGTM (Arrghh postfix again)

**Pull request merged**
