### PR TITLE
Fix Java11 Jira link

### PR DESCRIPTION
**Pull request by akedin**
Java 11 Jira link is broken

http://apache-beam-website-pull-requests.storage.googleapis.com/564/index.html

### CODE REVIEW

**Comment by akedin** [comment]
R: @melap

**Comment by melap** [comment]
retest this please

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
Looks like the eclipse site is having some trouble right now (can't get to that link from a browser either). I'll try again later today.

**Comment by melap** [comment]
@asfgit merge

**Pull request merged**
