### PR TITLE
[BEAM-2727] Add build information to the vote email template

### PR DESCRIPTION
**Pull request by iemejia**
This is useful to validate the reproducibility of the Java artifacts

### CODE REVIEW

**Comment by iemejia** [comment]
R: @kennknowles

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/682/

Jenkins built the site at commit id 0c1e59f26e4b4cf616ebbe74db5be363c8de68c7 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/316/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by iemejia** [comment]
ping @kennknowles I would like that we do a first trial of this during the validation of the vote for 2.2.0.

**Comment by kennknowles** [comment]
Good idea.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by kennknowles** [comment]
I'm not sure that mergebot is healthy right now, so it might need a manual merge.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/703/

Jenkins built the site at commit id cf493dfdd483814a31221541905435e4b3a09645 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/316/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by iemejia** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/731/

Jenkins built the site at commit id a6b6e738bc53e1de6828c3ebf205fdd69953933d with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/316/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by iemejia** [comment]
@asfgit merge

**Pull request merged**
