### PR TITLE
Add JIRA template for post-commit failures

### PR DESCRIPTION
**Pull request by swegner**
Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/PULL_REQUEST_NUMBER/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by swegner** [comment]
R: @Ardagan

**Comment by Ardagan** [comment]
I suggest we use [this link](https://issues.apache.org/jira/secure/CreateIssueDetails!init.jspa?pid=12319527&issuetype=1&summary=%5BjobName%5D%5BTestName%5D%5BIsFlake%5D%20Failure%20summary&priority=3&components=12334203&description=%3CFailure%20summary%3E%0AFailing%20job%20url:%0AJob%20history%20url:%0ARelevant%20log:)

**Comment by swegner** [comment]
Nice! I've incorporated that and added it to the short-url https://s.apache.org/beam-test-failure; let me know what you think.

**Comment by swegner** [comment]
@asfgit merge

**Pull request merged**
