### PR TITLE
Add TODO with linked JIRA to update Docker documentation for Gradle.

### PR DESCRIPTION
**Pull request by swegner**

### CODE REVIEW

**Comment by swegner** [comment]
Adding a TODO so we don't forget to come back to it.

R: @melap 
CC: @iemejia

**Comment by melap** [comment]
Is it worth making this visible for anyone who visits the page and sees that it isn't updated? That way they can go look at the issue status themselves, sign up to help, etc. (also it's less "out of sight, out of mind" )
```
> Note: There is an open issue to update this page for Gradle build: [BEAM-4117](https://issues.apache.org/jira/browse/BEAM-4117).
```
(example of how the > prefixed note renders at https://beam.apache.org/documentation/io/testing/)

**Comment by swegner** [comment]
Love it. Updated. @melap

**Comment by melap** [comment]
Thanks, merged

**Pull request closed without merging**
