### PR TITLE
Fix SQL walkthrough documentation

### PR DESCRIPTION
**Pull request by gaborhermann**
http://apache-beam-website-pull-requests.storage.googleapis.com/490/index.html

### CODE REVIEW

**Comment by gaborhermann** [comment]
Should I also submit these changes to the [Beam code repository](https://github.com/apache/beam/blob/master/website/src/documentation/dsls/sql/walkthrough.md)? It's a bit confusing to have docs at two places. Could we remove the ones from the normal repo?

**Comment by melap** [comment]
@akedin or @apilloud - since it's SQL related, can you take a quick look at this?

Re: the different repos, you don't need to submit the changes to the main repo right now. There's currently work in progress to migrate the website to the main repo, and they needed a copy of the files to test the testing job changes/make sure the infra is set up correctly. After everything is working, the content will be synced up and the normal repo will be the new source.

**Comment by akedin** [comment]
Thank you for the PR!

* renaming of `RowType` to `Schema` was [already done](https://beam.apache.org/documentation/dsls/sql/walkthrough/) in [BEAM-4771](https://github.com/apache/beam-site/pull/495), please rebase to pull in these changes;

* replacing `BeamSql` with `SqlTransform` is not part of the current release (2.5.0):
  * it will be a part of the 2.6.0 release, which has just started and will take some time to complete.   I don't think we should fix the doc to match the unreleased SDK;
  * "Overview" page will also need to be updated to reflect this, in addition to "walkthrough";

**Comment by aaltay** [comment]
What is the status of this PR? Should we close it?

**Comment by akedin** [comment]
Yes, the guide was updated for 2.6.0 release in another PR. Closing this one.

Please re-open if this is incorrect.

**Pull request closed without merging**
