### PR TITLE
Capability matrix updates for sliding window support in Spark Runner

### PR DESCRIPTION
**Pull request by takidau**
- Add sliding window support for batch Spark runner.
- Center capability matrix (expand/collapse looks cleaner).
- Default to summary view (easier to grok).
- Add "Last updated" timestamp.

### CODE REVIEW

**Comment by amitsela** [comment]
+1 on sliding windows support for batch in the Spark runner

**Comment by evilsoapbox** [comment]
LGTM overall - my only question, should we explicitly define which versions of all of these we're using for the comparison? Do we always implicitly use the latest stable release, something else?

**Comment by davorbonaci** [comment]
LGTM.

(Good question regarding versioning. I don't think we need to worry about this before the first stable release of Beam. Before that, all information should refer to the most-recent state of the project. Once we release a stable version, perhaps an annotation would be appropriate. E.g., "available since version 1.2.3.")

**Comment by evilsoapbox** [comment]
@davorbonaci Sorry, should have been more specific. What about the other projects? We may want to mention specific (**stable**) releases for each runner so people see a Beam->Runner version compatibility matrix as well.

**Comment by davorbonaci** [comment]
Good point.

(I guess you probably meant Beam Runner -> Backend matrix, as opposed to Beam -> Runner, and to mention specific releases of each backend, right?)

Definitely a nice-to-have. (Not sure how easy is it to gather that information, however.)

**Comment by takidau** [comment]
Created [BEAM-166](https://issues.apache.org/jira/browse/BEAM-166) for version tracking in the matrix. Thanks!

**Pull request merged**
