### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by hadarhg**
- [x] Update the prose on the landing page
- [ ] Copy Blog & Twitter sections from /src/index.md
- [x] Update content in the slider News section (perhaps with Blog & Twitter) OR delete this section completely 
- [ ] Add drop-downs to header sections (Get Started, Documentation, and Contribution)

### CODE REVIEW

**Comment by hadarhg** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
retest this please

**Comment by davorbonaci** [comment]
CC: @jbonofre 

@jbonofre, this is modifying the `v2` site. I think this is an improvement and since you are travelling, I'll merge it. If you have any comments, let's make sure we take them into account in a follow up pull request.

**Comment by davorbonaci** [comment]
LGTM. Merging.

**Comment by jbonofre** [comment]
@davor thanks ! No problem !

**Pull request closed without merging**
