### PR TITLE
Update Eclipse documentation for Gradle build.

### PR DESCRIPTION
**Pull request by swegner**

### CODE REVIEW

**Comment by swegner** [comment]
R: @melap

**Comment by melap** [comment]
@asfgit merge

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by swegner** [comment]
hrm.. I'm not familiar with this process. @melap let me know if there's anything you need from me to unblock this merge.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by swegner** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: User swegner not a committer on beam-website or not registered in gitbox.apache.org; access denied.

**Comment by swegner** [comment]
It was worth a try :)
@melap could you give the merge another try? I'm not sure why the previous verification job failed, but it looks like a flake: https://builds.apache.org/job/beam_PreCommit_Website_Merge/182

**Comment by melap** [comment]
hmm, they look like valid failures, but unrelated to your changes. I'll fix them up in another PR, and then manually merge that + this one. could you please squash the commits in the meantime? thanks!
- ./.testcontent/contribute/release-guide/index.html
  *  External link https://pypi.python.org/pypi?%3Aaction=register_form failed: 404 No error
- ./.testcontent/documentation/sdks/python-pipeline-dependencies/index.html
  *  External link https://pypi.python.org/pypi failed: 404 No error

**Comment by melap** [comment]
Oh, just noticed, could you also please remove the file changes in content/ as content/ is regenerated in a set environment by the system after merge.

**Comment by swegner** [comment]
squashed and reverted html files.

**Comment by melap** [comment]
thanks, #421 in progress!

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
The test failures are unrelated to this PR (slow webserver for a couple links, will hopefully resolve itself soon), so manually merged.

**Pull request closed without merging**
