### PR TITLE
Fix tox lint command in contribution guide

### PR DESCRIPTION
**Pull request by charlesccychen**
R: @melap

### CODE REVIEW

**Comment by melap** [comment]
I think this whole line is being removed in #412 by @udim

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Comment by melap** [comment]
Didn't notice this just changed the content directory -- content is autogenerated after merge, so you have to update the version in src. the other open PR that changes this modifies src so will merge that one and all should be well.

**Pull request closed without merging**
