### PR TITLE
Move Elasticsearch v5.x from in-progress to built-in

### PR DESCRIPTION
**Pull request by echauchot**
R: @jbonofre

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/704/

Jenkins built the site at commit id 151c470eb6a3f4612190b53f4c5b3063fac55b73 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/322/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by echauchot** [comment]
retest this please

**Comment by echauchot** [comment]
@jbonofre it seems that dead links check timeouts while checking jira URLs.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/705/

Jenkins built the site at commit id 151c470eb6a3f4612190b53f4c5b3063fac55b73 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/322/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by echauchot** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/709/

Jenkins built the site at commit id 151c470eb6a3f4612190b53f4c5b3063fac55b73 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/322/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 322 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm.apache.org/beam-website/322.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Comment by jbonofre** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by jbonofre** [comment]
It seems to fail on the M/R runner update:
```
- ./.testcontent/documentation/runners/mapreduce/index.html
  *  External link https://hadoop.apache.org/docs/r1.2.1/cluster_setup.html failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error
```
I'm checking why.

**Comment by echauchot** [comment]
ok thanks JB!

**Comment by jbonofre** [comment]
@echauchot can you do a rebase please ?

**Comment by echauchot** [comment]
@jbonofre done

**Comment by jbonofre** [comment]
@asfgit merge

**Comment by jbonofre** [comment]
I'm merging by hand.

**Pull request closed without merging**
