### PR TITLE
Publish 2.18.0 release

### PR DESCRIPTION
**Pull request by udim**

### CODE REVIEW

**Review by aaltay — APPROVED** [review]

**Comment by aaltay** [comment]
If you have not already, could you file a JIRA issue for having "snapshot" in the title of the javadocs?

**Comment by udim** [comment]
> snapshot

done

**Comment by udim** [comment]
> If you have not already, could you file a JIRA issue for having "snapshot" in the title of the javadocs?

done

**Comment by boyuanzz** [comment]
I have the same issue with SNAPSHOT in 2.19.0 release.

**Comment by boyuanzz** [comment]
Turns out adding `-PisRelease` to generating doc cmd helps to fix this issue. I'll update the script.

**Pull request merged**
