### PR TITLE
Remove extraneous type variable from StateSpec in state blog post

### PR DESCRIPTION
**Pull request by kennknowles**
R: @melap this makes the blog post use today's syntax; review largely FYI since it is just a code fix

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/724/

Jenkins built the site at commit id 3173aed1e82cb6690920cd2553b36ea45d5d32a3 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/327/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by melap** [comment]
thanks, the changes match the changes you made in the beam repo, so fwiw, seems consistent to me

**Comment by kennknowles** [comment]
R: @bjchambers for committer

**Comment by bjchambers** [comment]
LGTM

**Comment by kennknowles** [comment]
@asfgit merge

**Pull request closed without merging**
