### PR TITLE
Fix wrong gradle project targets in testing web-page.

### PR DESCRIPTION
**Pull request by HuangLED**
Make correct project name in testing command line. 

Once your pull request has been opened and assigned a number, please edit the
URL below, replacing `PULL_REQUEST_NUMBER` with the number of your pull request.

http://apache-beam-website-pull-requests.storage.googleapis.com/563/index.html

Finally, it will help us expedite review of your Pull Request if you tag
someone (e.g. @username) to look at it.

### CODE REVIEW

**Comment by melap** [comment]
R: @lukecwik

**Comment by HuangLED** [comment]
@Ardagan  to verify the fixes

**Comment by HuangLED** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: User HuangLED not a committer on beam-website or not registered in gitbox.apache.org; access denied.

**Comment by apilloud** [comment]
LGTM.

**Comment by apilloud** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Adding files from repository preparation failed. Please try again.

**Comment by Ardagan** [comment]
I'm confused. Did this succeed or not?

**Comment by apilloud** [comment]
Code is here: https://github.com/jasonkuster/merge-bot/blob/90c0f45a09afb72d88e0a580ab3f071a7017d9b3/mergebot_backend/merge.py#L165
@jasonkuster might know more?

**Comment by HuangLED** [comment]
Thanks for checking the PR folks! 

ps> Same confusion here, regarding how the bot asfgit behaves.

**Pull request closed without merging**
