### PR TITLE
Add portability to contribute section

### PR DESCRIPTION
**Pull request by herohde**
Adding back the link removed in previous PR

### CODE REVIEW

**Comment by herohde** [comment]
R: @melap

**Comment by melap** [comment]
retest this please

**Comment by melap** [comment]
@asfgit merge

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 344 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm.apache.org/beam-website/344.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
