### PR TITLE
Add James Xu(xumingming) as committer

### PR DESCRIPTION
**Pull request by xumingming**
R: @davorbonaci

### CODE REVIEW

**Comment by kennknowles** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/631/

Jenkins built the site at commit id d86e8992d89fb34fc59b66f25f2a9fd76af30ccb with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/281/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Fetch failed. Please try again.

**Pull request closed without merging**
