### PR TITLE
[BEAM-835] Added IntelliJ instructions to the contribution guide

### PR DESCRIPTION
**Pull request by minudika**
This PR is submitted replacing of PR #56. Pleas review..

### CODE REVIEW

**Comment by davorbonaci** [comment]
retest this please

**Comment by davorbonaci** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
I'm sorry for the delay on my part. @tgroh has kindly volunteered to review & merge. Thanks @minudika.

R: @tgroh

**Comment by tgroh** [comment]
Thanks for this!

LGTM; I've fiddled with a bit of the language before pushing.

**Pull request closed without merging**
