### PR TITLE
Clarify runtime type checking documentation

### PR DESCRIPTION
**Pull request by charlesccychen**
R: @robertwb

### CODE REVIEW

**Comment by robertwb** [comment]
LGTM

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 385 in state failure with description Final push failed, but verification succeeded. This may have occurred because of a manual merge into the repo. Please check logs and try again.. URL: http://mergebot-vm2.apache.org/beam-website/385.

**Comment by asfgit** [comment]
Error: Final push failed, but verification succeeded. This may have occurred because of a manual merge into the repo. Please check logs and try again.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Couldn't complete force push to verification branch. Please try again.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
