### PR TITLE
Fix broken links due to code directory moves

### PR DESCRIPTION
**Pull request by melap**
Fix broken links due to apache/beam#4479 and apache/beam#4467. This PR:
- Updates example links from java8 to java
- Updates hadoop/input-format to hadoop-input-format

### CODE REVIEW

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 380 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/maven-box/job/maven-assembly-plugin/api/python?tree=jobs%5Bname%2Ccolor%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f614d0d7150>: Failed to establish a new connection: [Errno 111] Connection refused',)).. URL: http://mergebot-vm2.apache.org/beam-website/380.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/maven-box/job/maven-assembly-plugin/api/python?tree=jobs%5Bname%2Ccolor%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f614d0d7150>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 380 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6147abf990>: Failed to establish a new connection: [Errno 111] Connection refused',)).. URL: http://mergebot-vm2.apache.org/beam-website/380.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6147abf990>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 380 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6147658750>: Failed to establish a new connection: [Errno 111] Connection refused',)).. URL: http://mergebot-vm2.apache.org/beam-website/380.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6147658750>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 380 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f614749ba90>: Failed to establish a new connection: [Errno 111] Connection refused',)).. URL: http://mergebot-vm2.apache.org/beam-website/380.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f614749ba90>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 380 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f61475f0610>: Failed to establish a new connection: [Errno 111] Connection refused',)).. URL: http://mergebot-vm2.apache.org/beam-website/380.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f61475f0610>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 380 in state error with description Unexpected Error: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6147fd6ad0>: Failed to establish a new connection: [Errno 111] Connection refused',)).. URL: http://mergebot-vm2.apache.org/beam-website/380.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: HTTPSConnectionPool(host='builds.apache.org', port=443): Max retries exceeded with url: /job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6147fd6ad0>: Failed to establish a new connection: [Errno 111] Connection refused',)).

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Pull request merged**
