### PR TITLE
[BEAM-2853] Fix left menu in nexmark page

### PR DESCRIPTION
**Pull request by echauchot**
R: @iemejia

### CODE REVIEW

**Comment by iemejia** [comment]
Retest this please

**Comment by iemejia** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by iemejia** [comment]
Argh this failed because of verification found deadlinks to the old git repository (http://git-wip-us...). Please rebase once the PR that fixes this is merged.

**Comment by echauchot** [comment]
@iemejia rebased on asf-site now that url fix PR is merged

**Comment by iemejia** [comment]
@asfgit merge

**Pull request merged**
