### PR TITLE
[BEAM-3123] update status of BEAM-1035 and BEAM-1037 in Nexmark

### PR DESCRIPTION
**Pull request by echauchot**
R: @iemejia

### CODE REVIEW

**Comment by echauchot** [comment]
retest this please

**Comment by echauchot** [comment]
Errors seem unrelated to this PR:
1. staging error is due to:
```
[beam_PreCommit_Website_Stage] $ /bin/bash -xe /tmp/jenkins7430890935655500896.sh
+ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpgkeys: key 409B6B1796C275462A1703113804BB82D39DC0E3 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Build step 'Execute shell' marked build as failure

```
2. dead links error is due to:
```
Error:  Could not locate the included file 'capability-matrix-common.md' in any of ["/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Website_Test/src/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
rake aborted!
```

**Comment by melap** [comment]
retest this please

**Comment by echauchot** [comment]
retest this please

**Comment by echauchot** [comment]
build is pending for some days, I guess there is a jenkins problem ongoing.

**Comment by jbonofre** [comment]
R: @jbonofre

I gonna take a look. Sorry about that.

**Comment by echauchot** [comment]
thanks @jbonofre I cannot have access to the infra.

**Pull request closed without merging**
