### PR TITLE
Update site to mention the 2 Python lint envs

### PR DESCRIPTION
**Pull request by holdenk**
Update the site to mention the 2 Python lint enviroments.

### CODE REVIEW

**Comment by holdenk** [comment]
cc @aaltay

**Comment by aaltay** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 396 in state failure with description Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.. URL: http://mergebot-vm2.apache.org/beam-website/396.

**Comment by asfgit** [comment]
Error: Timed out trying to find verification job. Check Jenkins (https://builds.apache.org/job/beam_PreCommit_Website_Merge/) to ensure job is configured correctly.

**Comment by aaltay** [comment]
@melap is the merge bot working? Do we need to merge manually?

**Comment by melap** [comment]
This particular failure was because there were no free machines to run the verification job before it timed out. I usually just check https://builds.apache.org/label/beam/load-statistics?auto_refresh=false and see if there is a queue and there currently is, so running it now would likely end in the same failure. I'll try it again when some machines free up.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
two link failures that aren't really dead linkes, will keep trying periodically...
External link http://calcite.apache.org failed: got a time out (response code 0)

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: Custom preparation command failed. Check logs for more information.

**Comment by melap** [comment]
yeah, I think this may need a manual merge at the moment. finally got past the transient erroneous link test errors (rake test issue) but now have hit mergebot issue.

**Comment by aaltay** [comment]
I merged it manually.

**Pull request closed without merging**
