### PR TITLE
Add MapReduce and Tez runners to ongoing projects.

### PR DESCRIPTION
**Pull request by peihe**

### CODE REVIEW

**Comment by peihe** [comment]
R: @kennknowles

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/601/

Jenkins built the site at commit id da270b5b851ff8ca7df5f4ff1761e3591d9a54fd with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/282/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by peihe** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/602/

Jenkins built the site at commit id da270b5b851ff8ca7df5f4ff1761e3591d9a54fd with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/282/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by kennknowles** [comment]
Well, LGTM even if that didn't work.

**Comment by peihe** [comment]
sent https://github.com/apache/beam-site/pull/283 for fixing the dead link.

**Comment by peihe** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/612/

Jenkins built the site at commit id 37eb2d2b11a83275ed6b8aa6ecebc55a2a95775d with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/282/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by peihe** [comment]
retest this please

**Comment by peihe** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/625/

Jenkins built the site at commit id 37eb2d2b11a83275ed6b8aa6ecebc55a2a95775d with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/282/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by peihe** [comment]
@asfgit merge

**Pull request closed without merging**
