### PR TITLE
[BEAM-857] Add IntelliJ Checkstyle documentation

### PR DESCRIPTION
**Pull request by swegner**

### CODE REVIEW

**Comment by swegner** [comment]
R: @kennknowles

**Comment by davorbonaci** [comment]
retest this please

**Comment by kennknowles** [comment]
LGTM. I actually just blasted past that screen without thinking. I'll merge it I think. Travis failures are timeouts in link checking for links that are not part of your PR.

**Comment by davorbonaci** [comment]
(See #56 also.)

**Comment by nssalian** [comment]
Perhaps combine both #55 and this one. Both look good and necessary.

**Comment by kennknowles** [comment]
We need the content of both #55 and #56. These are good additions. Merging this just because it arrived first.

**Pull request merged**
