### PR TITLE
[BEAM-2869] Add dates to releases on downloads page

### LINKED ISSUE #312: Releases are not dated on the site
I think it should be easier to see on the site the dates when Beam versions were released. There are no dates in the downloads list:
https://beam.apache.org/get-started/downloads/
Nor in any release notes:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12319527&version=12340528

### PR DESCRIPTION
**Pull request by melap**
resolves #312

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/684/

Jenkins built the site at commit id 620e76105b556caa4c74a56fd1827bb4b4dc7fb5 with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/318/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 318 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/43/api/python?depth=1&tree=building.. URL: http://mergebot-vm.apache.org/beam-website/318.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/43/api/python?depth=1&tree=building.

**Comment by tgroh** [comment]
@asfgit merge

**Pull request closed without merging**
