### PR TITLE
Travis CI YAML config

### PR DESCRIPTION
**Pull request by james-malone**
Adding a Travis CI configuration file so we can use Travis on the Beam website.

### CODE REVIEW

**Comment by davorbonaci** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
We need travis turned on for the repo before we can see whether this works.

**Comment by dhalperi** [comment]
(but this looks perfectly reasonable)

**Comment by dhalperi** [comment]
Filed [INFRA-12202](https://issues.apache.org/jira/browse/INFRA-12202) to request Travis be enabled.

**Comment by dhalperi** [comment]
Hi James,

INFRA-12202 has been implemented, so Travis is enable-able for this repo. Can you re-issue this PR (aka close and reopen, perhaps you might have to rebase and push) and see if Travis runs?

Thanks,
Dan

**Pull request closed without merging**
