### PR TITLE
[BEAM-3852] Update slack channel link and slack invite for new channel.

### PR DESCRIPTION
**Pull request by lukecwik**

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @melap

**Comment by lukecwik** [comment]
@asfgit merge

**Comment by asfgit** [comment]
MergeBot: Merge: PR 401 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm2.apache.org:8080/beam-website/401.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Comment by asfgit** [comment]
MergeBot: Merge: PR 401 in state error with description Unexpected Error: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.. URL: http://mergebot-vm2.apache.org:8080/beam-website/401.

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/job/beam_PreCommit_Website_Merge/api/python?tree=builds%5Bnumber%2Curl%5D.

**Pull request merged**
