### PR TITLE
Cleanup now that GitHub is not the mirror.

### PR DESCRIPTION
**Pull request by robertwb**

### CODE REVIEW

**Comment by melap** [comment]
retest this please

**Comment by robertwb** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: MergeBot encountered an unexpected error while processing this PR: 502 Server Error: Proxy Error for url: https://builds.apache.org/api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D.

**Comment by melap** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: PR failed in verification; check the Jenkins job for more information.

**Comment by melap** [comment]
@asfgit merge

**Pull request closed without merging**
