### PR TITLE
[BEAM-4157] Add Go quickstart and documentation

### PR DESCRIPTION
**Pull request by herohde**

### CODE REVIEW

**Comment by kennknowles** [comment]
Since you wrote this, the mailing list stuff is moved to `community/contact-us` which is also just `community/`

**Comment by herohde** [comment]
Thanks @kennknowles! Where do you find the links for the staged site, btw?

**Comment by kennknowles** [comment]
This looks really good. It fits in nicely and fleshes out the Beam story. Since _I_ like it a lot and I don't see WANT_LGTM=ALL I am going to go ahead :-)

Feel free to continue to send revisions.

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by herohde** [comment]
Thanks!

**Pull request closed without merging**
