### PR TITLE
Beam Summit Europe blogpost

### PR DESCRIPTION
**Pull request by matthiasa4**
This PR consists of:
- the blogpost announcing the Beam Summit Europe
- an update to the authors
- an image with the flyer of the sumimit

### CODE REVIEW

**Comment by pabloem** [comment]
Can you squeeze your commits?

**Comment by griscz** [comment]
@asfgit merge

**Comment by asfgit** [comment]
Error: User griscz not a committer on beam-website or not registered in gitbox.apache.org; access denied.

**Comment by matthiasa4** [comment]
@pabloem thanks! I have made a new PR: https://github.com/apache/beam-site/pull/542

**Pull request closed without merging**
