### PR TITLE
Replacing dead link for DoFnTester example.

### PR DESCRIPTION
**Pull request by swegner**

### CODE REVIEW

**Comment by swegner** [comment]
R: @kennknowles 

Using `v2.4.0` for stable permalink. However also means that the code example may not reflect any new API changes. Thoughts?

**Comment by timrobertson100** [comment]
This is the same as https://github.com/apache/beam-site/pull/448 but we opted for different links - your version seems like a better permalink (it's intuitive for one thing)

I don't see an easy alternative approach so LGTM

CC @iemejia - note same as the one you reviewed yesterday

**Comment by kennknowles** [comment]
Previously I was just saying "LGTM" to fixing the link, but now that I see what a minor entry it is, let's delete that row of the table.

**Comment by swegner** [comment]
Removed. PTAL @kennknowles

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
@asfgit merge

**Comment by iemejia** [comment]
It seems there is an issue with mergebot, can someone take a look and can we find a way to make this stable too. It is been easily more than 6 months with frequent issues with mergebot.

**Comment by swegner** [comment]
@iemejia agreed. I believe there are very few individuals with access or expertise necessary to maintain mergebot (i.e. maybe just @jasonkuster)

I've been doing some investigation this week on how we can make this process more reliable. I plan on starting a discussion on dev@ today or tomorrow.

**Comment by swegner** [comment]
In the meantime, is it possible to manually merge? Should I generate the HTML locally and push it to this branch? /cc @kennknowles @melap

**Comment by kennknowles** [comment]
Yes, any committer can manually merge and generate content. That used to be the norm. We have just gotten used to our sweet sweet automated life.

**Comment by kennknowles** [comment]
Best not to push generated content, so it forces it to happen as part of the merge process.

**Comment by jasonkuster** [comment]
Kicked the bot, let's give this another try.

**Comment by jasonkuster** [comment]
@asfgit merge

**Pull request merged**
