### PR TITLE
[BEAM-2800] Revamp sections 1 and 2 of DSL SQL docs:

### PR DESCRIPTION
**Pull request by takidau**
- Expand BeamRecord docs
- Expand examples

### CODE REVIEW

**Comment by takidau** [comment]
R: @XuMingmin @xumingming

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/646/

Jenkins built the site at commit id 658a0ed50a54d116101998b2dd62fb95772066fc with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/299/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by takidau** [comment]
The dead links are Javadoc references that won't be live until the merge to master. Options are: 

1. Leave them and maybe add a note at the top
2. Remove them and open a JIRA to fix it once the merge is done.

Thoughts?

**Comment by takidau** [comment]
Also, please note the TODO in one of the examples, @XuMingmin. Is that something we can actually do currently, or should I remove that example entirely?

**Comment by XuMingmin** [comment]
IMO let's keep the link as we expect it works soon.

For the TODO part, I don't think it works now, it's part of CLI plan.

**Comment by takidau** [comment]
TODO removed. Thanks!

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Website_Stage/648/

Jenkins built the site at commit id 95c01933d3d42c8dc79cd262c27355eb9a93ae6c with Jekyll and staged it [here](http://apache-beam-website-pull-requests.storage.googleapis.com/299/index.html). Happy reviewing.

Note that any previous site has been deleted. This staged site will be automatically deleted after its TTL expires. Push any commit to the pull request branch or re-trigger the build to get it staged again.

**Comment by XuMingmin** [comment]
@asfgit merge

**Pull request merged**
